# Site Settings
title: SolarIS
description: Solar Energy For Everyone
baseurl: ""
logo: /media/logo.png

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - github-pages
