# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_name', models.CharField(default='', max_length=255)),
                ('efficiency', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('rated_power', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('website', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
    ]
