# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='panel_name',
            new_name='package_name',
        ),
    ]
